# Generated by Django 4.2.1 on 2023-05-13 16:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='Nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Charactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='Nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='Nomi')),
            ],
        ),
        migrations.CreateModel(
            name='Manufactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Haqida')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test1.country', verbose_name='Ishlab chiqligan')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('sale_count', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Skidka Narxi')),
                ('view_count', models.PositiveBigIntegerField(default=0, verbose_name="Ko'rganlar soni")),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati Aktiv')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test1.category', verbose_name='Kategoriya')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test1.country', verbose_name='Ishlab chiqligan davlat')),
                ('manufactory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufactory', to='test1.manufactory', verbose_name='Ishlab chiqqan Korxona')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.UUIDField(default=uuid.UUID('61427daa-01ef-48e2-a275-3917994d60f6'), unique=True, verbose_name='Takrorlanmas_id')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Narxi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati Aktiv')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test1.product', verbose_name='Mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='product/media', verbose_name='Video/Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Holati Aktiv')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productmedia', to='test1.product', verbose_name='Mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCharactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('charactory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test1.charactory', verbose_name='Mahsulot xususiyati')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productcharactory', to='test1.product', verbose_name='Mahsulot')),
            ],
        ),
    ]
