# Generated by Django 4.2.1 on 2023-05-13 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categoriya'},
        ),
        migrations.AlterModelOptions(
            name='charactory',
            options={'verbose_name_plural': 'Xil(xususiyat)'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Davlat'},
        ),
        migrations.AlterModelOptions(
            name='manufactory',
            options={'verbose_name_plural': 'Ishlab Chiqqan Zavod'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Mahsulot'},
        ),
        migrations.AlterModelOptions(
            name='productcharactory',
            options={'verbose_name_plural': 'Mahsulot xususiyati'},
        ),
        migrations.AlterModelOptions(
            name='productmedia',
            options={'verbose_name_plural': 'Mahsulot Video/rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name_plural': 'Mahsulot Narxlari'},
        ),
        migrations.AlterField(
            model_name='productprice',
            name='unit_name',
            field=models.UUIDField(default=uuid.UUID('d683a114-2805-43b0-a211-44aa5aa82f6c'), unique=True, verbose_name='Takrorlanmas_id'),
        ),
    ]
