# Generated by Django 4.2.1 on 2023-05-13 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_alter_productprice_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='unit_name',
            field=models.UUIDField(default=uuid.UUID('3d644232-0736-482f-8051-85c6bf34cd3c'), unique=True, verbose_name='Takrorlanmas_id'),
        ),
    ]
