# Generated by Django 4.2.1 on 2023-05-13 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_alter_productprice_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='unit_name',
            field=models.UUIDField(default=uuid.UUID('55df92d6-1907-4442-802d-7237acfe9071'), unique=True, verbose_name='Takrorlanmas_id'),
        ),
    ]
